version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST:-mysql}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-appdb}
      DB_PORT: ${DB_PORT:-3306}
      INIT_ADMIN: ${INIT_ADMIN:-}
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql-data:
